--CREATE DATABASE BIBLIOTECA


CREATE TABLE ESTANTE
(CODLIVRO INT IDENTITY(1,1) PRIMARY KEY,
LIVRO VARCHAR(100) NOT NULL,
AUTOR VARCHAR(50) NOT NULL,
EDITORA VARCHAR(30) NOT NULL,
ANODEPUBLICACAO VARCHAR(20) NOT NULL,
NUMERODEPAGINA INT NOT NULL,
CLASSIFICACAO VARCHAR(40) NOT NULL,
DATADEAQUISICAO DATETIME NOT NULL,
OBSERVACAO VARCHAR(50))